# Generated by Django 6.0.6 on 2026-06-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactCheckClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_claim', models.TextField(help_text='The raw statistic or statement pulled from the PDF text.')),
                ('verdict', models.CharField(blank=True, choices=[('Verified', 'Verified'), ('Inaccurate', 'Inaccurate'), ('False', 'False')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('corrected_fact', models.TextField(blank=True, help_text='The actual factual info retrieved from the Tavily search layer.', null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='verifier.uploadeddocument')),
            ],
        ),
    ]
